name = "Ben Server 1.19.2"
author = "MasterHdom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e896ea8fd9e91f31b6bb23f7b07b0696279ad8eb9c429c9d62faf93d2096311c"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
