name = "Ben Server 1.19.2"
author = "MasterHdom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "864b65b39f5d3ef072bfbf1813e0db0317492c5abdc1002476241395f43d8311"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
